<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet id (amino-acid|nucleotide) #REQUIRED
                   length CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  min_width,
  max_width,
  minic,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  prob,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  seqfrac,
  strands,
  priors_file,
  reason_for_stopping,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT minic (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT prob (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT seqfrac (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="4.9.1" release="Fri Aug 23 16:49:42 2013 +1000">
<training_set datafile="/home/users/tndoo/ApplicatieCou11/WC_output1.fa" length="147">
<alphabet id="nucleotide" length="4">
<letter id="letter_A" symbol="A"/>
<letter id="letter_C" symbol="C"/>
<letter id="letter_G" symbol="G"/>
<letter id="letter_T" symbol="T"/>
</alphabet>
<ambigs>
<letter id="letter_B" symbol="B"/>
<letter id="letter_D" symbol="D"/>
<letter id="letter_H" symbol="H"/>
<letter id="letter_K" symbol="K"/>
<letter id="letter_M" symbol="M"/>
<letter id="letter_N" symbol="N"/>
<letter id="letter_R" symbol="R"/>
<letter id="letter_S" symbol="S"/>
<letter id="letter_U" symbol="U"/>
<letter id="letter_V" symbol="V"/>
<letter id="letter_W" symbol="W"/>
<letter id="letter_Y" symbol="Y"/>
<letter id="letter_star" symbol="*"/>
<letter id="letter_-" symbol="-"/>
<letter id="letter_X" symbol="X"/>
</ambigs>
<sequence id="sequence_0" name="lp_0026" length="100" weight="1.000000" />
<sequence id="sequence_1" name="lp_0028" length="100" weight="1.000000" />
<sequence id="sequence_2" name="lp_0057" length="100" weight="1.000000" />
<sequence id="sequence_3" name="lp_0081" length="100" weight="1.000000" />
<sequence id="sequence_4" name="lp_0107" length="100" weight="1.000000" />
<sequence id="sequence_5" name="lp_0111" length="100" weight="1.000000" />
<sequence id="sequence_6" name="lp_0126" length="100" weight="1.000000" />
<sequence id="sequence_7" name="lp_0158" length="100" weight="1.000000" />
<sequence id="sequence_8" name="lp_0183" length="100" weight="1.000000" />
<sequence id="sequence_9" name="lp_0197" length="100" weight="1.000000" />
<sequence id="sequence_10" name="lp_0231" length="100" weight="1.000000" />
<sequence id="sequence_11" name="lp_0236" length="100" weight="1.000000" />
<sequence id="sequence_12" name="lp_0304" length="100" weight="1.000000" />
<sequence id="sequence_13" name="lp_0311" length="100" weight="1.000000" />
<sequence id="sequence_14" name="lp_0325" length="100" weight="1.000000" />
<sequence id="sequence_15" name="lp_0339" length="100" weight="1.000000" />
<sequence id="sequence_16" name="lp_0354" length="100" weight="1.000000" />
<sequence id="sequence_17" name="lp_0367" length="100" weight="1.000000" />
<sequence id="sequence_18" name="lp_0455" length="100" weight="1.000000" />
<sequence id="sequence_19" name="lp_0472" length="100" weight="1.000000" />
<sequence id="sequence_20" name="lp_0505" length="100" weight="1.000000" />
<sequence id="sequence_21" name="lp_0533" length="100" weight="1.000000" />
<sequence id="sequence_22" name="lp_0536" length="100" weight="1.000000" />
<sequence id="sequence_23" name="lp_0538" length="100" weight="1.000000" />
<sequence id="sequence_24" name="lp_0556" length="100" weight="1.000000" />
<sequence id="sequence_25" name="lp_0561" length="100" weight="1.000000" />
<sequence id="sequence_26" name="lp_0575" length="100" weight="1.000000" />
<sequence id="sequence_27" name="lp_0688" length="100" weight="1.000000" />
<sequence id="sequence_28" name="lp_0690" length="100" weight="1.000000" />
<sequence id="sequence_29" name="lp_0691" length="100" weight="1.000000" />
<sequence id="sequence_30" name="lp_0698" length="100" weight="1.000000" />
<sequence id="sequence_31" name="lp_0729" length="100" weight="1.000000" />
<sequence id="sequence_32" name="lp_0758" length="100" weight="1.000000" />
<sequence id="sequence_33" name="lp_0764" length="100" weight="1.000000" />
<sequence id="sequence_34" name="lp_0771" length="100" weight="1.000000" />
<sequence id="sequence_35" name="lp_0785" length="100" weight="1.000000" />
<sequence id="sequence_36" name="lp_0804" length="100" weight="1.000000" />
<sequence id="sequence_37" name="lp_0817" length="100" weight="1.000000" />
<sequence id="sequence_38" name="lp_0822" length="100" weight="1.000000" />
<sequence id="sequence_39" name="lp_0854" length="100" weight="1.000000" />
<sequence id="sequence_40" name="lp_0856" length="100" weight="1.000000" />
<sequence id="sequence_41" name="lp_0858" length="100" weight="1.000000" />
<sequence id="sequence_42" name="lp_0875" length="100" weight="1.000000" />
<sequence id="sequence_43" name="lp_0907" length="100" weight="1.000000" />
<sequence id="sequence_44" name="lp_0926" length="100" weight="1.000000" />
<sequence id="sequence_45" name="lp_0947" length="100" weight="1.000000" />
<sequence id="sequence_46" name="lp_0954" length="100" weight="1.000000" />
<sequence id="sequence_47" name="lp_1001" length="100" weight="1.000000" />
<sequence id="sequence_48" name="lp_1002" length="100" weight="1.000000" />
<sequence id="sequence_49" name="lp_1003" length="100" weight="1.000000" />
<sequence id="sequence_50" name="lp_1079" length="100" weight="1.000000" />
<sequence id="sequence_51" name="lp_1101" length="100" weight="1.000000" />
<sequence id="sequence_52" name="lp_1125" length="100" weight="1.000000" />
<sequence id="sequence_53" name="lp_1164" length="100" weight="1.000000" />
<sequence id="sequence_54" name="lp_1169" length="100" weight="1.000000" />
<sequence id="sequence_55" name="lp_1250" length="100" weight="1.000000" />
<sequence id="sequence_56" name="lp_1314" length="100" weight="1.000000" />
<sequence id="sequence_57" name="lp_1354" length="100" weight="1.000000" />
<sequence id="sequence_58" name="lp_1355" length="100" weight="1.000000" />
<sequence id="sequence_59" name="lp_1427" length="100" weight="1.000000" />
<sequence id="sequence_60" name="lp_1430" length="100" weight="1.000000" />
<sequence id="sequence_61" name="lp_1443" length="100" weight="1.000000" />
<sequence id="sequence_62" name="lp_1543" length="100" weight="1.000000" />
<sequence id="sequence_63" name="lp_1546" length="100" weight="1.000000" />
<sequence id="sequence_64" name="lp_1564" length="100" weight="1.000000" />
<sequence id="sequence_65" name="lp_1611" length="100" weight="1.000000" />
<sequence id="sequence_66" name="lp_1648" length="100" weight="1.000000" />
<sequence id="sequence_67" name="lp_1668" length="100" weight="1.000000" />
<sequence id="sequence_68" name="lp_1747" length="100" weight="1.000000" />
<sequence id="sequence_69" name="lp_1795" length="100" weight="1.000000" />
<sequence id="sequence_70" name="lp_1833" length="100" weight="1.000000" />
<sequence id="sequence_71" name="lp_1835" length="100" weight="1.000000" />
<sequence id="sequence_72" name="lp_1913" length="100" weight="1.000000" />
<sequence id="sequence_73" name="lp_1931" length="100" weight="1.000000" />
<sequence id="sequence_74" name="lp_1947" length="100" weight="1.000000" />
<sequence id="sequence_75" name="lp_1994" length="100" weight="1.000000" />
<sequence id="sequence_76" name="lp_2015" length="100" weight="1.000000" />
<sequence id="sequence_77" name="lp_2056" length="100" weight="1.000000" />
<sequence id="sequence_78" name="lp_2099" length="100" weight="1.000000" />
<sequence id="sequence_79" name="lp_2114" length="100" weight="1.000000" />
<sequence id="sequence_80" name="lp_2121" length="100" weight="1.000000" />
<sequence id="sequence_81" name="lp_2128" length="100" weight="1.000000" />
<sequence id="sequence_82" name="lp_2141" length="100" weight="1.000000" />
<sequence id="sequence_83" name="lp_2166" length="100" weight="1.000000" />
<sequence id="sequence_84" name="lp_2217" length="100" weight="1.000000" />
<sequence id="sequence_85" name="lp_2263" length="100" weight="1.000000" />
<sequence id="sequence_86" name="lp_2280" length="100" weight="1.000000" />
<sequence id="sequence_87" name="lp_2325" length="100" weight="1.000000" />
<sequence id="sequence_88" name="lp_2333" length="100" weight="1.000000" />
<sequence id="sequence_89" name="lp_2334" length="100" weight="1.000000" />
<sequence id="sequence_90" name="lp_2509" length="100" weight="1.000000" />
<sequence id="sequence_91" name="lp_2515" length="100" weight="1.000000" />
<sequence id="sequence_92" name="lp_2541" length="100" weight="1.000000" />
<sequence id="sequence_93" name="lp_2573" length="100" weight="1.000000" />
<sequence id="sequence_94" name="lp_2585" length="100" weight="1.000000" />
<sequence id="sequence_95" name="lp_2613" length="100" weight="1.000000" />
<sequence id="sequence_96" name="lp_2631" length="100" weight="1.000000" />
<sequence id="sequence_97" name="lp_2645" length="100" weight="1.000000" />
<sequence id="sequence_98" name="lp_2652" length="100" weight="1.000000" />
<sequence id="sequence_99" name="lp_2683" length="100" weight="1.000000" />
<sequence id="sequence_100" name="lp_2704" length="100" weight="1.000000" />
<sequence id="sequence_101" name="lp_2710" length="100" weight="1.000000" />
<sequence id="sequence_102" name="lp_2714" length="100" weight="1.000000" />
<sequence id="sequence_103" name="lp_2771" length="100" weight="1.000000" />
<sequence id="sequence_104" name="lp_2776" length="100" weight="1.000000" />
<sequence id="sequence_105" name="lp_2786" length="100" weight="1.000000" />
<sequence id="sequence_106" name="lp_2799" length="100" weight="1.000000" />
<sequence id="sequence_107" name="lp_2804" length="100" weight="1.000000" />
<sequence id="sequence_108" name="lp_2818" length="100" weight="1.000000" />
<sequence id="sequence_109" name="lp_2824" length="100" weight="1.000000" />
<sequence id="sequence_110" name="lp_2843" length="100" weight="1.000000" />
<sequence id="sequence_111" name="lp_2860" length="100" weight="1.000000" />
<sequence id="sequence_112" name="lp_2906" length="100" weight="1.000000" />
<sequence id="sequence_113" name="lp_2924" length="100" weight="1.000000" />
<sequence id="sequence_114" name="lp_2931" length="100" weight="1.000000" />
<sequence id="sequence_115" name="lp_2940" length="100" weight="1.000000" />
<sequence id="sequence_116" name="lp_2956" length="100" weight="1.000000" />
<sequence id="sequence_117" name="lp_2963" length="100" weight="1.000000" />
<sequence id="sequence_118" name="lp_2968" length="100" weight="1.000000" />
<sequence id="sequence_119" name="lp_2992" length="100" weight="1.000000" />
<sequence id="sequence_120" name="lp_3006" length="100" weight="1.000000" />
<sequence id="sequence_121" name="lp_3019" length="100" weight="1.000000" />
<sequence id="sequence_122" name="lp_3049" length="100" weight="1.000000" />
<sequence id="sequence_123" name="lp_3059" length="100" weight="1.000000" />
<sequence id="sequence_124" name="lp_3077" length="100" weight="1.000000" />
<sequence id="sequence_125" name="lp_3094" length="100" weight="1.000000" />
<sequence id="sequence_126" name="lp_3174" length="100" weight="1.000000" />
<sequence id="sequence_127" name="lp_3204" length="100" weight="1.000000" />
<sequence id="sequence_128" name="lp_3205" length="100" weight="1.000000" />
<sequence id="sequence_129" name="lp_3207" length="100" weight="1.000000" />
<sequence id="sequence_130" name="lp_3236" length="100" weight="1.000000" />
<sequence id="sequence_131" name="lp_3246" length="100" weight="1.000000" />
<sequence id="sequence_132" name="lp_3259" length="100" weight="1.000000" />
<sequence id="sequence_133" name="lp_3284" length="100" weight="1.000000" />
<sequence id="sequence_134" name="lp_3312" length="100" weight="1.000000" />
<sequence id="sequence_135" name="lp_3324" length="100" weight="1.000000" />
<sequence id="sequence_136" name="lp_3330" length="100" weight="1.000000" />
<sequence id="sequence_137" name="lp_3334" length="100" weight="1.000000" />
<sequence id="sequence_138" name="lp_3360" length="100" weight="1.000000" />
<sequence id="sequence_139" name="lp_3404" length="100" weight="1.000000" />
<sequence id="sequence_140" name="lp_3411" length="100" weight="1.000000" />
<sequence id="sequence_141" name="lp_3440" length="100" weight="1.000000" />
<sequence id="sequence_142" name="lp_3573" length="100" weight="1.000000" />
<sequence id="sequence_143" name="lp_3579" length="100" weight="1.000000" />
<sequence id="sequence_144" name="lp_3665" length="100" weight="1.000000" />
<sequence id="sequence_145" name="lp_3675" length="100" weight="1.000000" />
<sequence id="sequence_146" name="lp_3687" length="100" weight="1.000000" />
<letter_frequencies>
<alphabet_array>
<value letter_id="letter_A">0.332</value>
<value letter_id="letter_C">0.144</value>
<value letter_id="letter_G">0.202</value>
<value letter_id="letter_T">0.321</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme /home/users/tndoo/ApplicatieCou11/WC_output1.fa -oc /home/users/tndoo/ApplicatieCou11/WC_output1 -dna -mod zoops -minw 35 -maxw 45 </command_line>
<host>hlo-ws131316</host>
<type>zoops</type>
<nmotifs>1</nmotifs>
<evalue_threshold>inf</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<min_width>35</min_width>
<max_width>45</max_width>
<minic>    0.00</minic>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<minsites>2</minsites>
<maxsites>147</maxsites>
<wnsites>0.8</wnsites>
<prob>1</prob>
<spmap>uni</spmap>
<spfuzz>0.5</spfuzz>
<prior>dirichlet</prior>
<beta>0.01</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_sequences>147</num_sequences>
<num_positions>14700</num_positions>
<seed>0</seed>
<seqfrac>       1</seqfrac>
<strands>forward</strands>
<priors_file></priors_file>
<reason_for_stopping>Stopped because nmotifs = 1 reached.</reason_for_stopping>
<background_frequencies source="dataset with add-one prior applied">
<alphabet_array>
<value letter_id="letter_A">0.332</value>
<value letter_id="letter_C">0.145</value>
<value letter_id="letter_G">0.202</value>
<value letter_id="letter_T">0.321</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="1" width="38" sites="129" ic="13.8" re="10.6" llr="944" e_value="2.3e-056" bayes_threshold="7.9004" elapsed_time="5.364335">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="letter_A">-172</value>
<value letter_id="letter_C">-31</value>
<value letter_id="letter_G">-90</value>
<value letter_id="letter_T">107</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-125</value>
<value letter_id="letter_C">-105</value>
<value letter_id="letter_G">-62</value>
<value letter_id="letter_T">104</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-383</value>
<value letter_id="letter_C">3</value>
<value letter_id="letter_G">129</value>
<value letter_id="letter_T">5</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-21</value>
<value letter_id="letter_C">99</value>
<value letter_id="letter_G">-6</value>
<value letter_id="letter_T">-47</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">1</value>
<value letter_id="letter_C">91</value>
<value letter_id="letter_G">-54</value>
<value letter_id="letter_T">-33</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">4</value>
<value letter_id="letter_C">42</value>
<value letter_id="letter_G">-112</value>
<value letter_id="letter_T">21</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-14</value>
<value letter_id="letter_C">-41</value>
<value letter_id="letter_G">-90</value>
<value letter_id="letter_T">58</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-29</value>
<value letter_id="letter_C">10</value>
<value letter_id="letter_G">-54</value>
<value letter_id="letter_T">43</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-21</value>
<value letter_id="letter_C">78</value>
<value letter_id="letter_G">-71</value>
<value letter_id="letter_T">9</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-25</value>
<value letter_id="letter_C">48</value>
<value letter_id="letter_G">-12</value>
<value letter_id="letter_T">5</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-29</value>
<value letter_id="letter_C">69</value>
<value letter_id="letter_G">10</value>
<value letter_id="letter_T">-20</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-17</value>
<value letter_id="letter_C">82</value>
<value letter_id="letter_G">-6</value>
<value letter_id="letter_T">-33</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-47</value>
<value letter_id="letter_C">53</value>
<value letter_id="letter_G">15</value>
<value letter_id="letter_T">2</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-42</value>
<value letter_id="letter_C">73</value>
<value letter_id="letter_G">-25</value>
<value letter_id="letter_T">9</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">28</value>
<value letter_id="letter_C">53</value>
<value letter_id="letter_G">-1</value>
<value letter_id="letter_T">-79</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">46</value>
<value letter_id="letter_C">-31</value>
<value letter_id="letter_G">-18</value>
<value letter_id="letter_T">-37</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">41</value>
<value letter_id="letter_C">-31</value>
<value letter_id="letter_G">-71</value>
<value letter_id="letter_T">-1</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">28</value>
<value letter_id="letter_C">-31</value>
<value letter_id="letter_G">-46</value>
<value letter_id="letter_T">5</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-47</value>
<value letter_id="letter_C">-31</value>
<value letter_id="letter_G">-190</value>
<value letter_id="letter_T">88</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-17</value>
<value letter_id="letter_C">42</value>
<value letter_id="letter_G">50</value>
<value letter_id="letter_T">-51</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-310</value>
<value letter_id="letter_C">42</value>
<value letter_id="letter_G">-12</value>
<value letter_id="letter_T">86</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-196</value>
<value letter_id="letter_C">-41</value>
<value letter_id="letter_G">165</value>
<value letter_id="letter_T">-91</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-161</value>
<value letter_id="letter_C">87</value>
<value letter_id="letter_G">79</value>
<value letter_id="letter_T">-20</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-1366</value>
<value letter_id="letter_C">-122</value>
<value letter_id="letter_G">-470</value>
<value letter_id="letter_T">153</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">157</value>
<value letter_id="letter_C">-1366</value>
<value letter_id="letter_G">-470</value>
<value letter_id="letter_T">-537</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-51</value>
<value letter_id="letter_C">3</value>
<value letter_id="letter_G">-171</value>
<value letter_id="letter_T">80</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">121</value>
<value letter_id="letter_C">-76</value>
<value letter_id="letter_G">-90</value>
<value letter_id="letter_T">-305</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">92</value>
<value letter_id="letter_C">69</value>
<value letter_id="letter_G">-90</value>
<value letter_id="letter_T">-337</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-1366</value>
<value letter_id="letter_C">-1366</value>
<value letter_id="letter_G">-1366</value>
<value letter_id="letter_T">164</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">33</value>
<value letter_id="letter_C">-164</value>
<value letter_id="letter_G">25</value>
<value letter_id="letter_T">-12</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">81</value>
<value letter_id="letter_C">-164</value>
<value letter_id="letter_G">-18</value>
<value letter_id="letter_T">-73</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">36</value>
<value letter_id="letter_C">-105</value>
<value letter_id="letter_G">-1</value>
<value letter_id="letter_T">-9</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">49</value>
<value letter_id="letter_C">-31</value>
<value letter_id="letter_G">10</value>
<value letter_id="letter_T">-67</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">31</value>
<value letter_id="letter_C">3</value>
<value letter_id="letter_G">-6</value>
<value letter_id="letter_T">-37</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-90</value>
<value letter_id="letter_C">64</value>
<value letter_id="letter_G">-31</value>
<value letter_id="letter_T">43</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">22</value>
<value letter_id="letter_C">3</value>
<value letter_id="letter_G">34</value>
<value letter_id="letter_T">-62</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">44</value>
<value letter_id="letter_C">-90</value>
<value letter_id="letter_G">5</value>
<value letter_id="letter_T">-29</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">13</value>
<value letter_id="letter_C">-41</value>
<value letter_id="letter_G">-80</value>
<value letter_id="letter_T">36</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="letter_A">0.100775</value>
<value letter_id="letter_C">0.116279</value>
<value letter_id="letter_G">0.108527</value>
<value letter_id="letter_T">0.674419</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.139535</value>
<value letter_id="letter_C">0.069767</value>
<value letter_id="letter_G">0.131783</value>
<value letter_id="letter_T">0.658915</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.023256</value>
<value letter_id="letter_C">0.147287</value>
<value letter_id="letter_G">0.496124</value>
<value letter_id="letter_T">0.333333</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.286822</value>
<value letter_id="letter_C">0.286822</value>
<value letter_id="letter_G">0.193798</value>
<value letter_id="letter_T">0.232558</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.333333</value>
<value letter_id="letter_C">0.271318</value>
<value letter_id="letter_G">0.139535</value>
<value letter_id="letter_T">0.255814</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.341085</value>
<value letter_id="letter_C">0.193798</value>
<value letter_id="letter_G">0.093023</value>
<value letter_id="letter_T">0.372093</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.302326</value>
<value letter_id="letter_C">0.108527</value>
<value letter_id="letter_G">0.108527</value>
<value letter_id="letter_T">0.480620</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.271318</value>
<value letter_id="letter_C">0.155039</value>
<value letter_id="letter_G">0.139535</value>
<value letter_id="letter_T">0.434109</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.286822</value>
<value letter_id="letter_C">0.248062</value>
<value letter_id="letter_G">0.124031</value>
<value letter_id="letter_T">0.341085</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.279070</value>
<value letter_id="letter_C">0.201550</value>
<value letter_id="letter_G">0.186047</value>
<value letter_id="letter_T">0.333333</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.271318</value>
<value letter_id="letter_C">0.232558</value>
<value letter_id="letter_G">0.217054</value>
<value letter_id="letter_T">0.279070</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.294574</value>
<value letter_id="letter_C">0.255814</value>
<value letter_id="letter_G">0.193798</value>
<value letter_id="letter_T">0.255814</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.240310</value>
<value letter_id="letter_C">0.209302</value>
<value letter_id="letter_G">0.224806</value>
<value letter_id="letter_T">0.325581</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.248062</value>
<value letter_id="letter_C">0.240310</value>
<value letter_id="letter_G">0.170543</value>
<value letter_id="letter_T">0.341085</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.403101</value>
<value letter_id="letter_C">0.209302</value>
<value letter_id="letter_G">0.201550</value>
<value letter_id="letter_T">0.186047</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.457364</value>
<value letter_id="letter_C">0.116279</value>
<value letter_id="letter_G">0.178295</value>
<value letter_id="letter_T">0.248062</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.441860</value>
<value letter_id="letter_C">0.116279</value>
<value letter_id="letter_G">0.124031</value>
<value letter_id="letter_T">0.317829</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.403101</value>
<value letter_id="letter_C">0.116279</value>
<value letter_id="letter_G">0.147287</value>